language: cpp

notifications:
  email: false
  
branches:
    only:
        - master
        - release

addons:
    apt_packages:
        - lib32bz2-1.0
        - lib32ncurses5
        - lib32z1 
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise 
        packages:
            - gcc-7
            - g++-7
        
     

before_script:
    - wget  https://sourceforge.net/projects/raspberry-pi-cross-compilers/files/Raspberry%20Pi%20GCC%20Cross-Compilers/GCC%208.3.0/Raspberry%20Pi%202%2C%203/cross-gcc-8.3.0-pi_2-3.tar.gz/download
    - tar xf download
    - sudo mv cross-pi-gcc-8.3.0-1 /opt
    - echo 'export PATH=/opt/cross-pi-gcc-8.3.0-1/bin:$PATH' >> .profile  
    - echo 'export LD_LIBRARY_PATH=/opt/cross-pi-gcc-8.3.0-1/lib:$LD_LIBRARY_PATH' >> .profile
    - source .profile
    - arm-linux-gnueabihf-g++ -v
    - g++ -v
    - gcc -v

install:
    - cd ..
    - git clone --branch feature-pi_support_windows_gcc https://github.com/R2D2-2019/R2D2-build.git 
    - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-7 /usr/bin/gcc # Change symlinks of gcc to gcc-7
    - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-7 /usr/bin/g++
    - export PATH=$PATH:/usr/bin/g++:/usr/bin/gcc
    - sudo cp -r /usr/bin/gcc /bin/gcc
    - sudo cp -r /usr/bin/g++ /bin/g++
    
    
jobs:
    include:
        - script:
            - cd R2D2-build/modules
            - cp -r $TRAVIS_BUILD_DIR $PWD/test_module
            - cd test_module/test
            - make build 
            - make run
            - make clean
        - script:
            - cd R2D2-build/modules
            - cp -r $TRAVIS_BUILD_DIR $PWD/test_module
            - cd test_module/code
            - make build
            - make clean
        
